SEED = None

POPULATION_SIZE = 500
NUMBER_OF_GENERATIONS = 400

MUTATION_PROBABILITY = 0.05
CROSSOVER_PROBABILITY = 0.8

TOURNEY_SIZE = 5

WEIGHT = {
    'COMMON_POINTS': 10,
    'OUT_OF_BOUNDS_POINTS': 40,
    'PATHS_LENGTH': 0.2,
    'NUMBER_OF_SEGMENTS': 0.5
}
